spring:
  application.name: simple-rest-app
  datasource:
    driverClassName: org.postgresql.Driver
    url: "jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}"
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

management.endpoints.spring.cloud.bus:
  refresh.enabled: "true"
  env.enabled: "true"

mybatis:
  mapperLocations: "classpath:mybatis/mapper/*mapper.xml"
  type-aliases-package: az.cybernet.vis.simplerest.dto
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

server:
  servlet:
    context-path: /
    
logging:
  level:
    az.cybernet.vis.simplerest.infrastructure.repository.mapper: DEBUG
    
vis:
  jwt:
    secret: "MIIEpAIBAAKCAQEA69c+tsnjtUXpglNLgv1x7/3on7ABFdSEJcv2T2DYnzx2NkEZHeBrFgd2LcoYOSCqk35lv0BqPEAsqNMsK42EJ9TWNLBj71eropXAANN8g2UvKIU7N4bsSvfy+DQrHzQvvZEaK8YYTPy66WiXurAzt9u4abVCxxhCPfr9PyYH9ixAPXucME5muKFYagdb51Kr5qFCn3jp2rMoEh1pNU8mfevfg4b0b7lBHQ5vV0I9NCCApXINLvz3l6l0CbC5p0JiHnye37YMJkSCXcI3rgGdw4jlHOla5BxOTCvTV9hIo4FGEXRpXxZ8OtQSblstpozTUZLwT9srAy1DNJ83Mr85WQIDAQABAoIBAHSP2tAu8ltapXGjR3QDXbfWz411SOQIOBQSPbe3zvjMwkRIYmiQzXyCzZcOBnDdw1DIrPMcnCURNsFuNauE8ydYm1JJR+s4cn0V9GK0JBsw/GDTkJP+HHVlHPItno56lYnk2IGAE+yhEKRh7HP5uGYLs5aTXuDWDY9iqJ34ZwD0pQxmVrZPTB6LIby657eNJIX8RtOjV8hXoGqBVSfLyEoae52QujXiv+sS4VLAqSYTXYNWgWmGQ+qY1ncEa1ONgJ/bqqQuna7Gy2eLwJ6Ne4gbUnuR3WfFDoYw5JC0JiCx7k50IfRJ66l10+/N7JSMSII7FMQXSl1WsVd42+VVjj0CgYEA+12MTt361bO+mCY4kGr0NTLJub1einOjSqX2FXeobjqNDlN16Xa5ww4I+5uhgQBYXmgtQzEW09Z7tlSxfPl6YILOPC38E75FcmqPdBFSvAGjAlSBwe30KP0v/ms03U78iDOuTXD1ADCL052zrGxSVdq8XHlHuudPSMJTlhbdJBMCgYEA8DBrlSSQxGqVyQPbJvz1e1lFLC05SZ2FcjgkpINK9dTwA2Xax5lV0LLGKITVYXUJTP/Nt8o6maKmULZDMibU4StrJ643HUPFacsicztT77ncgfuDbv9KHslHMV+8/v/C/TOL24unsWzBTI/g/8wSUQbtyjZhgB3BbP1Uuy5JYmMCgYEApGJyPqWGw7jPvRrJxRBc8mlraQ/BwxOKx2evfiyJtsSNuL+2Dd757ui/0SPfQ8jhAaRpbVauEg1jTEMo640PjgwdKVf9UUAOlJvBgutNSuxbGUwAq72c/i1N9LlRkiV0mvIJXFWxs9ULrHGmre0ND16D7onV8hIRVIjZNv9u0YcCgYEAjMYkV959htFdhtpeuOQr0KbKtxCuceoEC6TCPTXCWoD6R1OMPc4uEMqm/5qTIbKhx+JppR2+6Mr+pXGdwqglvu9et3wRS3KsIsxvHZCZKnkJt5k9OHIh9BdORa7yK5alpxduEjgxCflO9duiKOpnldv0xL7IuHk4I/P6lFaVpjcCgYBA3W3aMkP6zWb4FQh7JlqPbVF2MbafFtMlA35tmj9Xm/mAWq8/mlhkoW7FSO6v8Qj+hT/NaeDzZMrLY1zR6/XfPdQe2eQhKlkE1FKALOh8AP9Dub8e+j3pP26mlDv8RKNx0A68+kwa1oCxlw12A/yjEn9+4F/+YuCCxPKtQa/pcQ=="
